# Generated by Django 3.1.7 on 2021-03-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_displayusername'),
    ]

    operations = [
        migrations.DeleteModel(
            name='displayusername',
        ),
    ]
