# Generated by Django 3.1.7 on 2021-03-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20210327_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.DeleteModel(
            name='Following',
        ),
    ]
